//! `cite.lock`: the news row each episode was deployed as, per Supabase project (committed like `Cargo.lock`).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::core::CiteError;

pub const LOCKFILE_NAME: &str = "cite.lock";

const HEADER: &str = "\
# Generated by `cite deploy`: the Supabase news id each episode was deployed as.
# Commit this file so every machine updates the same news rows.
# Removing an entry makes the next deploy publish that episode as a new item.

";

#[derive(Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Lockfile {
    backends: BTreeMap<String, BTreeMap<String, i64>>,
}

impl Lockfile {
    fn path(root: &Path) -> PathBuf {
        root.join(LOCKFILE_NAME)
    }

    pub fn load(root: &Path) -> Result<Self, CiteError> {
        let path = Self::path(root);
        match std::fs::read_to_string(&path) {
            Ok(text) => toml::from_str(&text)
                .map_err(|e| CiteError::Config(format!("{} is not valid: {e}", path.display()))),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(e.into()),
        }
    }

    pub fn save(&self, root: &Path) -> Result<(), CiteError> {
        let body = toml::to_string(self)?;
        std::fs::write(Self::path(root), format!("{HEADER}{body}"))?;
        Ok(())
    }

    pub fn news_id(&self, backend: &str, file: &str) -> Option<i64> {
        self.backends.get(backend)?.get(file).copied()
    }

    pub fn set_news_id(&mut self, backend: &str, file: &str, news_id: i64) {
        self.backends
            .entry(backend.to_string())
            .or_default()
            .insert(file.to_string(), news_id);
    }

    pub fn remove_news_ids(&mut self, backend: &str, news_ids: &[i64]) {
        if let Some(files) = self.backends.get_mut(backend) {
            files.retain(|_, id| !news_ids.contains(id));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BACKEND: &str = "https://abc.supabase.co";

    #[test]
    fn test_round_trip_is_human_readable() {
        let dir = tempfile::tempdir().unwrap();
        let mut lock = Lockfile::default();
        lock.set_news_id(BACKEND, "content/episode-one.md", 12);
        lock.set_news_id(BACKEND, "content/episode-two.md", 13);
        lock.save(dir.path()).unwrap();

        let text = std::fs::read_to_string(dir.path().join(LOCKFILE_NAME)).unwrap();
        assert!(text.starts_with("# Generated by `cite deploy`"));
        assert!(text.contains("[\"https://abc.supabase.co\"]"), "{text}");
        assert!(text.contains("\"content/episode-one.md\" = 12"), "{text}");

        let loaded = Lockfile::load(dir.path()).unwrap();
        assert_eq!(loaded, lock);
        assert_eq!(loaded.news_id(BACKEND, "content/episode-two.md"), Some(13));
        assert_eq!(
            loaded.news_id("https://other.co", "content/episode-two.md"),
            None
        );
    }

    #[test]
    fn test_missing_file_is_empty_and_invalid_file_errors() {
        let dir = tempfile::tempdir().unwrap();
        assert_eq!(Lockfile::load(dir.path()).unwrap(), Lockfile::default());

        std::fs::write(dir.path().join(LOCKFILE_NAME), "not = [valid").unwrap();
        let err = Lockfile::load(dir.path()).unwrap_err();
        assert!(err.to_string().contains("cite.lock"), "{err}");
    }

    #[test]
    fn test_remove_news_ids() {
        let mut lock = Lockfile::default();
        lock.set_news_id(BACKEND, "a.md", 1);
        lock.set_news_id(BACKEND, "b.md", 2);
        lock.remove_news_ids(BACKEND, &[1]);
        assert_eq!(lock.news_id(BACKEND, "a.md"), None);
        assert_eq!(lock.news_id(BACKEND, "b.md"), Some(2));
    }
}
