use std::fs;
use std::path::Path;
use tracing::info;

use crate::core::CiteError;
use crate::core::manifest::Manifest;
use crate::core::metadata::Metadata;

const AUTO_GEN_HEADER: &str = r#"# This file was autogenerated by cite init
# https://github.com/laezyAI/cite
#
# Copyright 2026, Binay Pradhan
# SPDX-License-Identifier: MIT

"#;

pub fn init_project(name: &str, root: &Path) -> Result<(), CiteError> {
    if !root.exists() {
        fs::create_dir_all(root)?;
        info!("Created directory: {}", root.display());
    }

    for sub in ["content", "assets/audio", "assets/image"] {
        let path = root.join(sub);
        if !path.exists() {
            fs::create_dir_all(&path)?;
            info!("Created directory: {sub}");
        }
    }

    let manifest_path = root.join("cite.toml");
    if !manifest_path.exists() {
        fs::write(&manifest_path, manifest_template(name)?)?;
        info!("Created file: cite.toml");
    } else {
        info!("Skipped: cite.toml (already exists)");
    }

    let meta_path = root.join("metadata.yml");
    if !meta_path.exists() {
        fs::write(&meta_path, metadata_template()?)?;
        info!("Created file: metadata.yml");
    } else {
        info!("Skipped: metadata.yml (already exists)");
    }

    let gitignore_path = root.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(&gitignore_path, format!("{AUTO_GEN_HEADER}\nbuild/\n"))?;
        info!("Created file: .gitignore");
    } else {
        info!("Skipped: .gitignore (already exists)");
    }

    Ok(())
}

fn manifest_template(name: &str) -> Result<String, CiteError> {
    let manifest = Manifest::default_template(name);
    let body = toml::to_string(&manifest)?;
    Ok(format!("{AUTO_GEN_HEADER}\n{body}"))
}

fn metadata_template() -> Result<String, CiteError> {
    let meta = Metadata::default();
    let body = serde_yaml::to_string(&meta)?;
    Ok(format!(
        "{AUTO_GEN_HEADER}# Add your podcast entries below. Each entry becomes one episode.\n\
#   title:     Display title of the episode\n\
#   file:      Path to the Markdown source\n\
#   source_url: Original URL (optional)\n\
#   category:  Category name (optional)\n\
#   thumbnail: Path under assets/image (optional)\n\
#   audio:     Path under assets/audio (optional)\n\
#   timeline:  Mixed list of one BibTeX citation file and news item ids\n\
{}\n",
        body.trim_end(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_init_project_creates_structure() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("my-project");
        init_project("my-project", &root).unwrap();
        assert!(root.join("cite.toml").exists());
        assert!(root.join("metadata.yml").exists());
        assert!(root.join("content").is_dir());
        assert!(root.join("assets/audio").is_dir());
        assert!(root.join("assets/image").is_dir());
        assert!(root.join(".gitignore").exists());
    }

    #[test]
    fn test_init_project_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("existing");
        init_project("existing", &root).unwrap();
        // second call should not error
        init_project("existing", &root).unwrap();
        assert!(root.join("cite.toml").exists());
    }

    #[test]
    fn test_init_project_generates_toml() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("generated");
        init_project("generated", &root).unwrap();
        let content = std::fs::read_to_string(root.join("cite.toml")).unwrap();
        assert!(content.contains("generated"));
        assert!(content.contains("[project]"));
        assert!(content.contains("[build]"));
    }

    #[test]
    fn test_manifest_template_produces_valid_toml() {
        let t = manifest_template("test-name").unwrap();
        let manifest: Manifest = toml::from_str(&t).unwrap();
        assert_eq!(manifest.project.name, "test-name");
        assert_eq!(manifest.build.compiler_version, 1.0);
        assert!(manifest.build.incremental);
    }
}
