//! Project scaffolding: new projects from `cite init` and restores from the local snapshot (assets are re-added by hand).

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use tracing::info;

use crate::core::CiteError;
use crate::core::bibtex;
use crate::core::db::DbManager;
use crate::core::manifest::{Manifest, ProjectConfig};
use crate::core::metadata::{Metadata, Podcast, TimelineEntry, TimelineItem};

const AUTO_GEN_HEADER: &str = r#"# This file was autogenerated by cite init
# https://github.com/laezyAI/cite
#
# Copyright 2026, Binay Pradhan
# SPDX-License-Identifier: MIT

"#;

pub fn init_project(name: &str, root: &Path) -> Result<(), CiteError> {
    if !root.exists() {
        fs::create_dir_all(root)?;
        info!("Created directory: {}", root.display());
    }

    for sub in ["content", "assets/audio", "assets/image"] {
        let path = root.join(sub);
        if !path.exists() {
            fs::create_dir_all(&path)?;
            info!("Created directory: {sub}");
        }
    }

    let manifest_path = root.join("cite.toml");
    if !manifest_path.exists() {
        fs::write(&manifest_path, manifest_template(name)?)?;
        info!("Created file: cite.toml");
    } else {
        info!("Skipped: cite.toml (already exists)");
    }

    let meta_path = root.join("metadata.yml");
    if !meta_path.exists() {
        fs::write(&meta_path, metadata_template()?)?;
        info!("Created file: metadata.yml");
    } else {
        info!("Skipped: metadata.yml (already exists)");
    }

    let gitignore_path = root.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(
            &gitignore_path,
            format!(
                "{AUTO_GEN_HEADER}\n# Commit cite.lock; these are local build and deploy state.\nbuild/\n.cite/\n"
            ),
        )?;
        info!("Created file: .gitignore");
    } else {
        info!("Skipped: .gitignore (already exists)");
    }

    Ok(())
}

pub struct RestoreSummary {
    pub podcasts: usize,
    pub timeline_events: usize,
    pub warnings: Vec<String>,
}

pub async fn restore_project(
    db: &DbManager,
    project_id: &str,
    target: &Path,
) -> Result<RestoreSummary, CiteError> {
    let snapshot = db.get_restore_snapshot(project_id).await?;
    fs::create_dir_all(target.join("content"))?;

    let manifest = Manifest {
        project: ProjectConfig {
            name: snapshot.name.clone(),
            language: snapshot.language.clone(),
            metadata_file: snapshot.metadata_file.clone(),
            artist_id: snapshot.artist_id.clone(),
        },
        ..Default::default()
    };
    fs::write(target.join("cite.toml"), toml::to_string_pretty(&manifest)?)?;

    let mut citations_by_podcast: HashMap<&str, Vec<&TimelineEntry>> = HashMap::new();
    for timeline in snapshot.timelines.iter().filter(|t| t.from_citation) {
        citations_by_podcast
            .entry(timeline.podcast_id.as_str())
            .or_default()
            .push(&timeline.entry);
    }

    let mut warnings = Vec::new();
    let mut podcasts = Vec::new();
    for pod in snapshot.podcasts.iter().filter(|p| !p.file.is_empty()) {
        match &pod.content {
            Some(content) => write_file(&target.join(&pod.file), content)?,
            None => warnings.push(format!("Content missing for '{}'; re-add it", pod.title)),
        }
        for asset in [&pod.audio, &pod.thumbnail].into_iter().flatten() {
            warnings.push(format!("Re-add asset {asset}"));
        }
        let citation = pod.citation_file.as_deref().filter(|c| !c.is_empty());
        if let Some(citation) = citation {
            let entries = citations_by_podcast.get(pod.id.as_str()).cloned();
            let bib = bibtex::render(entries.unwrap_or_default());
            write_file(&target.join(citation), &bib)?;
        }
        podcasts.push(pod.metadata.clone().unwrap_or_else(|| {
            Podcast {
                title: pod.title.clone(),
                file: pod.file.clone(),
                source_url: pod.source_url.clone(),
                category: pod.category.clone(),
                thumbnail: pod.thumbnail.clone(),
                audio: pod.audio.clone(),
                timeline: citation
                    .map(|file| vec![TimelineItem::Citation(file.to_string())])
                    .unwrap_or_default(),
                ..Default::default()
            }
        }));
    }

    let metadata = Metadata { podcasts };
    fs::write(
        target.join(&snapshot.metadata_file),
        serde_yaml::to_string(&metadata)?,
    )?;

    Ok(RestoreSummary {
        podcasts: snapshot.podcasts.len(),
        timeline_events: snapshot.timelines.len(),
        warnings,
    })
}

fn write_file(path: &Path, contents: &str) -> Result<(), CiteError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(())
}

fn manifest_template(name: &str) -> Result<String, CiteError> {
    let manifest = Manifest::default_template(name);
    let body = toml::to_string(&manifest)?;
    Ok(format!("{AUTO_GEN_HEADER}\n{body}"))
}

fn metadata_template() -> Result<String, CiteError> {
    let meta = Metadata::default();
    let body = serde_yaml::to_string(&meta)?;
    Ok(format!(
        "{AUTO_GEN_HEADER}# Add your podcast entries below. Each entry becomes one episode.\n\
#   title:      Display title of the episode (up to 500 characters)\n\
#   file:       Path to the Markdown source. It identifies the episode: deploying again\n\
#               updates the same news item (recorded in cite.lock), renaming the file\n\
#               publishes a new one\n\
#   category:   Category name, e.g. Politics (required; must exist in Supabase,\n\
#               upper/lower case does not matter)\n\
#   summary:    Short summary shown in the app, up to 50 words (optional; defaults to\n\
#               the first 50 words of the Markdown file)\n\
#   source_url: Original article link, e.g. www.example.com/story (optional)\n\
#   thumbnail:  Path under assets/image (optional)\n\
#   audio:      Path under assets/audio (optional)\n\
#   timeline:   Ordered list of related events; each entry is one of\n\
#                 - title: Bill passes the Senate      an event written here; date, url\n\
#                   date: May 22, 2025                 and description are optional\n\
#                   url: example.com/story\n\
#                 - content/refs.bib                   a BibTeX file (at most one) whose\n\
#                                                      entries become events\n\
#                 - content/other.md                   another episode of this project\n\
#                 - 42                                 the id of a news item already published\n\
#\n\
# Dates can be written as 2025, 2025-05, May 2025, 2025-05-22, 22 May 2025 or May 22, 2025.\n\
# A misspelled key is reported as an error rather than silently ignored.\n\
#\n\
# Example:\n\
# podcasts:\n\
#   - title: The week in AI\n\
#     file: content/week-in-ai.md\n\
#     category: Artificial Intelligence\n\
#     source_url: https://example.com/week-in-ai\n\
#     audio: assets/audio/week-in-ai.mp3\n\
#     timeline:\n\
#       - title: New model released\n\
#         date: 2025-05-22\n\
#         url: https://example.com/release\n\
{}\n",
        body.trim_end(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_restore_keeps_metadata_as_written() {
        let dir = tempfile::tempdir().unwrap();
        let src = dir.path().join("src");
        init_project("src", &src).unwrap();
        std::fs::write(src.join("content/ep.md"), "# Ep\nHello").unwrap();
        std::fs::write(
            src.join("content/ep.bib"),
            "@misc{a, title = {Paper}, year = {2020}}",
        )
        .unwrap();
        let metadata = r#"
podcasts:
  - title: Ep
    file: content/ep.md
    summary: Written by hand.
    category: tech
    timeline:
      - content/ep.bib
      - 26
      - title: Inline event
        date: 2025-05-22
"#;
        std::fs::write(src.join("metadata.yml"), metadata).unwrap();
        let ctx = crate::core::project::ProjectContext::load(&src).unwrap();
        let db = DbManager::open_path(&dir.path().join("cite.db"))
            .await
            .unwrap();
        crate::core::compiler::compile(&db, &ctx, true)
            .await
            .unwrap();

        let target = dir.path().join("restored");
        let summary = restore_project(&db, &ctx.project_id(), &target)
            .await
            .unwrap();
        assert_eq!(
            summary.timeline_events, 2,
            "citation entry and inline event"
        );

        let restored = crate::core::project::ProjectContext::load(&target).unwrap();
        let (a, b) = (&ctx.metadata.podcasts[0], &restored.metadata.podcasts[0]);
        assert_eq!(b.summary, a.summary);
        assert_eq!(b.timeline, a.timeline);
        let bib = std::fs::read_to_string(target.join("content/ep.bib")).unwrap();
        assert!(
            bib.contains("Paper") && !bib.contains("Inline event"),
            "{bib}"
        );
    }

    #[test]
    fn test_init_project_creates_structure() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("my-project");
        init_project("my-project", &root).unwrap();
        assert!(root.join("cite.toml").exists());
        assert!(root.join("metadata.yml").exists());
        assert!(root.join("content").is_dir());
        assert!(root.join("assets/audio").is_dir());
        assert!(root.join("assets/image").is_dir());
        assert!(root.join(".gitignore").exists());
    }

    #[test]
    fn test_init_project_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("existing");
        init_project("existing", &root).unwrap();
        init_project("existing", &root).unwrap();
        assert!(root.join("cite.toml").exists());
    }

    #[test]
    fn test_init_project_generates_toml() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("generated");
        init_project("generated", &root).unwrap();
        let content = std::fs::read_to_string(root.join("cite.toml")).unwrap();
        assert!(content.contains("generated"));
        assert!(content.contains("[project]"));
        assert!(content.contains("[build]"));
    }

    #[test]
    fn test_manifest_template_produces_valid_toml() {
        let t = manifest_template("test-name").unwrap();
        let manifest: Manifest = toml::from_str(&t).unwrap();
        assert_eq!(manifest.project.name, "test-name");
        assert_eq!(manifest.build.compiler_version, 1.0);
        assert!(manifest.build.incremental);
    }
}
